[ids]
# the role required to use the set-password command
required_role = 1234
# the channel that newcomers will use to enter the password
entry_channel = 5678
# the role that will be granted to people that entered the password
grant_role = 0987

[tokens]
discord = '...'
