# what to be sent in the entry channel when a new user joins
entry_message = """
"""

[ids]
# the role required to use the set-password command.
# this doesn't actually need to have administrator permissions,
# it's just a marker for the bot.
admin_role = 1234
# the channel that newcomers will use to enter the password
entry_channel = 5678
# the role that will be granted to people that entered the password
grant_role = 9876
# the role that will be removed when the grant role is granted
# set to 0 to disable
remove_role = 0

[tokens]
discord = '...'
